### ISSUE TITLE
Pivot Freezed Transform

### ISSUE THREAD

**Issue by jpvaillancourt** [Ziriax/Maya2glTF#12]
First of all, thanks for this wonderful job !

I have seen that the pivot that I have set in Maya doesn't export in the glTF file. I always setup my pivot and freeze all my transforms at the end of my asset's editing.  What's the best way to export with the pivot? I'm thinking about scripting a pivot group creator that will stand at the pivot place a offset the mesh inside.

Am I wrong?

**Comment by Ziriax** [comment]
Thanks for trying out Maya2glTF!

glTF doesn't have a concept of pivots, it only has transformation nodes. A pivot could be simulated by adding two extra nodes, but we currently do not support that.

But if you select your mesh, and export it, a glTF node should be exported for it. If you have frozen the transform, this node should represent the "pivot" of the mesh.

Is your glTF file missing this node?

**Comment by jpvaillancourt** [comment]
Thanks for the fast response.

Thats what I thought.

As for the transforms, they are frozen but the pivot is in the middle of
the bounding box instead of its original place.

**Comment by Ziriax** [comment]
That is interesting. I will debug this, since that is not the behaviour that I was expecting. When you rotate the glTF node, the mesh should rotate around the original pivot point. If not, that is a bug :-) Just for testing, does it work when you delete the history?

**Comment by Ziriax** [comment]
A bug indeed, I will fix this immediately, and at a test scene. Thanks for reporting!

**Comment by jpvaillancourt** [comment]
That is true. I worked on a partial JSON exporter (ThreeJS format) almost a year ago and I faced the same problem. My workaround was to create a node attached to every meshes that contains the extra informations (as meta data) needed for my particular needs. I thought of using it to enable / disable the creation of offset groups upon export for selected transform nodes. This might be a solution.

As for my scene, it has no transforms nor history. [https://ufile.io/jwpgz](Here it is) if you want to make some tests. The upload will expire in 30 days. You'll see the result when rotating "geo > porte_grp" on the Y axis.

About your solution, I'm gonna try it today and come back to you.

**Comment by Ziriax** [comment]
I released v0.9.1 that should address this, but of course this needs more testing. Feel free to try it :-)

PS: I have another large patch in the making to deal with segment scale compensation, that is related, but not ready yet...

**Comment by jpvaillancourt** [comment]
Just tried it. I have a C++ runtime error that crashes maya upon export.

Maya2glTF.mll
File : scr\ExportableNode.cpp
List : 88

Expression: MStatus::kSuccess == (_status_)

**Comment by Ziriax** [comment]
Yes, I noticed myself just a second again :-) Back to fixing.

**Comment by Ziriax** [comment]
I was able to export your model with my latest changes, I will make a release tomorrow.

May I ask what is the purpose of the pivots? Are you going to change the node rotations in Javascript?

**Comment by jpvaillancourt** [comment]
Exactly! Thanks for the updates :) Looking forward to use the latest release !

**Comment by Ziriax** [comment]
I added some extra features to help export your and similar models:

- automatic selection of all descendant meshes by default

- not exporting texture coordinates if no material has textures, unless explicitly requested (GLTF gives a warning otherwise)

- detecting and reporting invalid tangent vectors (your models don't have texture coordinates, and Maya seems to generate zero tangents for some vertices). Anyway I suggest to export these kind of unshaded models without tangents. Maybe excluding tangent vectors should be the default.

I'm now testing the exporter, but [you can download your exported model here](https://uploadfiles.io/6h6fj), so you can see if the pivots work out for you (I did not add extra nodes, just offsetted the vertices by the negative pivot, and prepended the pivot transform to each node's transform, to adjust the vertices again when transforming them).

I did receive the following errors from the exporter:

```
// Error: line 1: Transform 'pCube16' of mesh 'pCube16Shape' has different scaling and rotation pivots, this is not supported, ignoring scaling pivot! // 
// Error: line 1: Transform 'pCube26' of mesh 'pCube26Shape' has different scaling and rotation pivots, this is not supported, ignoring scaling pivot! // 
// Error: line 1: Transform 'pCube28' of mesh 'pCube28Shape' has different scaling and rotation pivots, this is not supported, ignoring scaling pivot! // 
// Error: line 1: Transform 'pCube30' of mesh 'pCube30Shape' has different scaling and rotation pivots, this is not supported, ignoring scaling pivot! // 
// Error: line 1: Transform 'pCube32' of mesh 'pCube32Shape' has different scaling and rotation pivots, this is not supported, ignoring scaling pivot! // 
// Error: line 1: Transform 'pCube34' of mesh 'pCube34Shape' has different scaling and rotation pivots, this is not supported, ignoring scaling pivot! // 
// Error: line 1: Transform 'pCube36' of mesh 'pCube36Shape' has different scaling and rotation pivots, this is not supported, ignoring scaling pivot! // 
// Error: line 1: Transform 'pCube38' of mesh 'pCube38Shape' has different scaling and rotation pivots, this is not supported, ignoring scaling pivot! // 
// Error: line 1: Transform 'pCube40' of mesh 'pCube40Shape' has different scaling and rotation pivots, this is not supported, ignoring scaling pivot! // 
// Error: line 1: Transform 'pCube42' of mesh 'pCube42Shape' has different scaling and rotation pivots, this is not supported, ignoring scaling pivot! // 
// Error: line 1: Transform 'pCube44' of mesh 'pCube44Shape' has different scaling and rotation pivots, this is not supported, ignoring scaling pivot! // 
// Error: line 1: Transform 'pCube46' of mesh 'pCube46Shape' has different scaling and rotation pivots, this is not supported, ignoring scaling pivot! // 
// Error: line 1: Transform 'pCube48' of mesh 'pCube48Shape' has different scaling and rotation pivots, this is not supported, ignoring scaling pivot! // 
```

As the error message hopefully indicates, I only convert the rotation pivot, not the scaling pivot.

**Comment by Ziriax** [comment]
Supported in v0.9.2
