### ISSUE TITLE
UI not refreshing

### ISSUE THREAD

**Issue by Ziriax** [Ziriax/Maya2glTF#17]
In v0.9.4, the UI is not updating when a new scene is loaded, or the current scene is modified.

Either add a `refresh` button, or subscribe to change events

**Comment by JunkYardRobotBoy** [comment]
@Ziriax I had that issue as well. But I re-installed it from the .bat file. Opened up Maya into a fresh scene and tested it the UI.  It worked fine. Then I re-opened my test scene and tested the UI. Export was successful!
I'm using Maya 2018.

**Comment by Ziriax** [comment]
@JunkYardRobotBoy Thanks for the info! Note that Maya2glTF currently doesn't perform any compression or optimization (besides using 16-bit indices if possible). You might want to explore [other tools like Cesium's pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline) for doing this, I haven't done that yet.
