### ISSUE TITLE
PBR OpenGL shader does not exist

### ISSUE THREAD

**Issue by Chase-Reid** [Ziriax/Maya2glTF#18]
As stated above I do not see the PBR OpenGL shader inside of this directory:
\Documents\maya\Maya2glTF\PBR\shaders\glTF_PBR.ogsfx

I did not attempt to compile my own version of the plugin. I downloaded the v0.9.4 BETA release. Perhaps that is the reason why. I also do not see it inside of the Maya2GLTF repo either. 

Could you provide me with some direction here to obtain the shader or could you add it to the repo?

**Comment by Ziriax** [comment]
It should be in the v0.9.5 release. I forgot to mention that.
