### ISSUE TITLE
PBR material is being imported as standard material in THREEjs

### ISSUE THREAD

**Issue by Chase-Reid** [Ziriax/Maya2glTF#20]
Hello,

Sorry in advance if this is a feature request and not a bug. Currently when I import a model into THREEjs editor its material is set to MESHSTANDARDMATERIAL. I am using the PBR material provided along with the exporter.  The behavior I would expect is for the material to be set as MESHPHYSICALMATERIAL upon import.

One of the big reasons we use MESHPHYSICALMATERIAL over standard is because ambient lights and hemisphere lights only affect MESHPHYSICALMATERIAL. We use these lights all the time and they play a key role in our artist toolset. 

Again this could be a feature request or possibly a bug with the maya material. Thanks in advance!

**Comment by Ziriax** [comment]
Can you give me the url of the editor you are using? We do export a valid PBR GLTF 2.0 material, at least according to the validator

**Comment by Ziriax** [comment]
I just looked at the three is docs, and the standard material seems the correct material, it is a metallic roughness PBR material:

https://threejs.org/docs/#api/materials/MeshStandardMaterial

The physical material just adds support for clear coat and a reflectivity factor, for things like car paint

Is it that support you want?

**Comment by Ziriax** [comment]
Anyway it is best to wait for a GLTF extension that supports clear coat, it seems to be mentioned [here](https://github.com/KhronosGroup/glTF/issues/1221) but I am not sure what the status is

**Comment by Ziriax** [comment]
> One of the big reasons we use MESHPHYSICALMATERIAL over standard is because ambient lights and hemisphere lights only affect MESHPHYSICALMATERIAL. We use these lights all the time and they play a key role in our artist toolset.

Are you sure about that? I know nothing about threejs besides having read book about it, but these two materials should be very similar.

Note that we are not exporting lights or environment maps, that is not part of the GLTF 2.0 spec. When using threejs, you would have to write code for that. Is it these kind of GLTF extensions you are looking for Maya2glTF to support? See the discussion [here](https://github.com/KhronosGroup/glTF/issues/946)

Maybe you should ask this question in the threejs forum, to figure out what is not working, providing a scene exported with Maya2gltf.

**Comment by Chase-Reid** [comment]
To answer your first comment I am using the following editor: https://threejs.org/editor/

**Comment by Ziriax** [comment]
You could ask the threejs guys if it possible to force the creation of a physical material when loading glTF.

In this threejs example, you can see in the code that the environment map is set on each material. Also hemisphere lights are used. https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_gltf.html

I will indeed close this issue since I can't do much about this I'm afraid.

**Comment by donmccurdy** [comment]
Chiming in late to say yes, feel free to file an issue against three.js for this. I think MeshStandardMaterial is the right default, but you may be able to convert at load time:

```
object.traverse((node) => {
  if (node.isMesh) {
    node.material = new THREE.MeshPhysicalMaterial().copy( node.material );
  }
});
```

^If that doesn't work, I would consider it a bug on three.js.
