### ISSUE TITLE
BaseColorFactor inside the glTF_PBR.ogsfx shader is not being exported

### ISSUE THREAD

**Issue by Chase-Reid** [Ziriax/Maya2glTF#25]
STEPS:
1. Create new maya scene
2. Click CREATE -> Polygon Primitives -> Cube
3. Launch maya2glTF UI and click ASSIGN PBR SHADER TO SELECTION
4. Modify BASE COLOR FACTOR to any RGB value other than 255, 255, 255
5. Select the Cube mesh in the viewport
6. Inside the maya2glTF UI click EXPORT SELECTED MESHES
7. Import exported GLTF into a GLTF viewer or ThreeJS editor

RESULT:
BASE COLOR FACTOR  value is not exported.

As an artist I expect this value to directly correlated to COLOR attribute inside of THREEjs editor. Even though I modify this value inside the material in Maya, the COLOR attribute inside of THREEjs editor defaults to 255, 255, 255.

![image](https://user-images.githubusercontent.com/26173435/40813711-27325d22-64f1-11e8-864e-eb989db30924.png)

![image](https://user-images.githubusercontent.com/26173435/40813691-134cabb4-64f1-11e8-9161-c727b94c3977.png)

**Comment by Ziriax** [comment]
Indeed. That did work in the past. I will fix this ASAP. Again, really should make time for unit tests...

**Comment by Ziriax** [comment]
@Chase-Reid Could you try the newly released 0.9.6? I don't have a lot of time for deep testing right now, but it seemed to work with my test scene. Thanks!
