### ISSUE TITLE
Transparent base-color-texture does not change material alphaMode to BLEND

### ISSUE THREAD

**Issue by Ziriax** [Ziriax/Maya2glTF#26]
Currently the only way to set the `alphaMode` of a material to `BLEND` is by setting the base color opacity to something `< 1`.

<del>We should either expose the `alphaMode` as an attribute, scan all the pixels of the base-color-texture, or provide both</del>

When the `Technique` is set to `Transparent`, the `alphaMode` must be set to `BLEND`

**Comment by Chase-Reid** [comment]
Ive changed the (alpha) value of the base color to 0.721 to get the result you see below.

**Comment by Ziriax** [comment]
Nice looking car!

I will add some test scenes for this.

I'll keep you posted

**Comment by Ziriax** [comment]
What glTF viewer are you using?

**Comment by Chase-Reid** [comment]
Thank you very much sir! 

I am using this viewer:
https://gltf-viewer.donmccurdy.com/

**Comment by Ziriax** [comment]
I verified this is a regression bug, I will release a fix soon

**Comment by Ziriax** [comment]
See the V0.9.7 release. Closing this issue, will re-open it if still buggy. 

Many thanks for reporting this!
