### ISSUE TITLE
Invalid Zip file for 0.9.7-BETA Release

### ISSUE THREAD

**Issue by robertlong** [Ziriax/Maya2glTF#30]
When opening the zip file in Windows it shows an error message: "The Compressed (zipped) folder is invalid".

**Comment by Ziriax** [comment]
I'm using WinRAR to create these ZIP files, but it seems the generated files are not valid, although WinRAR can open these. Most likely my batch file creates RAR files with the ZIP extension, I'll fix this ASAP.

I've replaced the ZIP file in the release with one that GNU's unzip.exe can extract, does this work for you now?

**Comment by robertlong** [comment]
Yes, it works now. Thank you!
